"""Engine-owned backend-neutral rendering contracts."""

from ludoweave.render.api import RenderBackend, RenderDescriptor
from ludoweave.render.backends import NullRenderBackend, NullRenderDevice
from ludoweave.render.contracts import (
    BlendMode,
    BufferData,
    BufferDescriptor,
    BufferUsage,
    CaptureImage,
    ClearCommand,
    Color,
    CommandList,
    DebugLineCommand,
    DiagnosticTextCommand,
    PipelineDescriptor,
    PrimitiveTopology,
    RenderCapabilities,
    SpriteBatchCommand,
    SpriteInstance,
    Submission,
    SurfaceDescriptor,
    SurfaceKind,
    TextureData,
    TextureDescriptor,
    TextureFormat,
    TextureUsage,
    TileBatchCommand,
    TileInstance,
)
from ludoweave.render.device import RenderDevice
from ludoweave.render.extraction import (
    Camera2D,
    PresentationFrame,
    RenderExtractor,
    SpriteDrawGroup,
    SpriteExtractionSource,
    TileDrawGroup,
)
from ludoweave.render.graph import (
    CompiledRenderGraph,
    GraphResource,
    GraphResourceKind,
    GraphResourceLifetime,
    RenderGraph,
    RenderPass,
)
from ludoweave.render.handles import (
    BufferHandle,
    FenceHandle,
    PipelineHandle,
    RenderResourceHandle,
    SurfaceHandle,
    TextureHandle,
)

__all__ = [
    "BlendMode",
    "BufferData",
    "BufferDescriptor",
    "BufferHandle",
    "BufferUsage",
    "Camera2D",
    "CaptureImage",
    "ClearCommand",
    "Color",
    "CommandList",
    "CompiledRenderGraph",
    "DebugLineCommand",
    "DiagnosticTextCommand",
    "FenceHandle",
    "GraphResource",
    "GraphResourceKind",
    "GraphResourceLifetime",
    "NullRenderBackend",
    "NullRenderDevice",
    "PipelineDescriptor",
    "PipelineHandle",
    "PresentationFrame",
    "PrimitiveTopology",
    "RenderBackend",
    "RenderCapabilities",
    "RenderDescriptor",
    "RenderDevice",
    "RenderExtractor",
    "RenderGraph",
    "RenderPass",
    "RenderResourceHandle",
    "SpriteBatchCommand",
    "SpriteDrawGroup",
    "SpriteExtractionSource",
    "SpriteInstance",
    "Submission",
    "SurfaceDescriptor",
    "SurfaceHandle",
    "SurfaceKind",
    "TextureData",
    "TextureDescriptor",
    "TextureFormat",
    "TextureHandle",
    "TextureUsage",
    "TileBatchCommand",
    "TileDrawGroup",
    "TileInstance",
]
